import os
import time
import subprocess
from pathlib import Path

from config import MOCK_BUILD


# ============================================================
# PROJECT TYPE DETECTION
# ============================================================

def detect_project(workspace):

    workspace = Path(workspace)

    if (workspace / "gradlew").exists():
        return "android"

    if (workspace / "pom.xml").exists():
        return "maven"

    if (workspace / "build.gradle").exists():
        return "gradle"

    if (workspace / "package.json").exists():
        return "node"

    if (workspace / "requirements.txt").exists():
        return "python"

    if (workspace / "CMakeLists.txt").exists():
        return "cmake"

    return "unknown"


# ============================================================
# FIND APK GENERATED BY CURRENT BUILD
# ============================================================

def find_apk(workspace, build_start_time=None):

    workspace = Path(workspace)

    apk_files = []

    for apk in workspace.rglob("*.apk"):

        # Ignore hidden/system-like directories.
        if any(part.startswith(".") for part in apk.parts):
            continue

        try:
            mtime = apk.stat().st_mtime
        except OSError:
            continue

        # If a build timestamp is supplied, only accept APKs
        # generated after the current build started.
        if build_start_time is not None:
            if mtime < build_start_time:
                continue

        apk_files.append(apk)

    if not apk_files:
        return None

    # Newest APK generated by this build.
    apk = max(
        apk_files,
        key=lambda path: path.stat().st_mtime
    )

    return str(apk)


# ============================================================
# REMOVE STALE APK OUTPUTS
# ============================================================

def remove_stale_apks(workspace):

    workspace = Path(workspace)

    removed = []

    for apk in workspace.rglob("*.apk"):

        try:
            apk.unlink()
            removed.append(str(apk))

        except OSError:
            # Do not fail the entire build because one old APK
            # cannot be removed.
            continue

    return removed


# ============================================================
# BUILD PROJECT
# ============================================================

def build_project(workspace):

    if MOCK_BUILD:

        return (
            True,
            None,
            "Mock build successful."
        )

    workspace = Path(workspace)

    if not workspace.exists():

        return (
            False,
            None,
            f"Workspace does not exist: {workspace}"
        )

    project = detect_project(workspace)

    if project == "unknown":

        return (
            False,
            None,
            "Unsupported project."
        )

    # --------------------------------------------------------
    # Remove stale APKs before an Android build.
    # This prevents VAMP from accidentally installing an old APK.
    # --------------------------------------------------------

    removed_apks = []

    if project == "android":

        removed_apks = remove_stale_apks(workspace)

    # --------------------------------------------------------
    # Record build start time.
    # --------------------------------------------------------

    build_start_time = time.time()

    # --------------------------------------------------------
    # Build commands
    # --------------------------------------------------------

    commands = {

        "android": [
            "./gradlew",
            "clean",
            "assembleDebug"
        ],

        "gradle": [
            "gradle",
            "build"
        ],

        "maven": [
            "mvn",
            "package"
        ],

        "python": [
            "python3",
            "-m",
            "pytest"
        ],

        "node": [
            "npm",
            "run",
            "build"
        ],

        "cmake": [
            "cmake",
            "--build",
            "."
        ],
    }

    cmd = commands[project]

    # --------------------------------------------------------
    # Android Gradle wrapper
    # --------------------------------------------------------

    if project == "android":

        gradlew = workspace / "gradlew"

        if not gradlew.exists():

            return (
                False,
                None,
                "gradlew not found."
            )

        try:
            os.chmod(
                gradlew,
                0o755
            )

        except OSError as exc:

            return (
                False,
                None,
                f"Unable to make gradlew executable: {exc}"
            )

    # --------------------------------------------------------
    # Execute build
    # --------------------------------------------------------

    print()
    print("Build command:")
    print(" ".join(cmd))

    try:

        result = subprocess.run(
            cmd,
            cwd=workspace,
            capture_output=True,
            text=True,
        )

    except Exception as exc:

        return (
            False,
            None,
            f"Build execution failed: {exc}"
        )

    stdout = result.stdout or ""
    stderr = result.stderr or ""

    logs = (
        f"PROJECT TYPE: {project}\n"
        f"BUILD START: {build_start_time}\n"
        f"BUILD RETURN CODE: {result.returncode}\n"
        f"\n===== STDOUT =====\n"
        f"{stdout}\n"
        f"\n===== STDERR =====\n"
        f"{stderr}\n"
    )

    # --------------------------------------------------------
    # Build failure
    # --------------------------------------------------------

    if result.returncode != 0:

        return (
            False,
            None,
            logs
        )

    # --------------------------------------------------------
    # Find APK generated by this build
    # --------------------------------------------------------

    apk_path = None

    if project == "android":

        apk_path = find_apk(
            workspace,
            build_start_time=build_start_time
        )

        if not apk_path:

            logs += (
                "\nERROR: Gradle build succeeded, "
                "but no newly generated APK was found."
            )

            return (
                False,
                None,
                logs
            )

    # --------------------------------------------------------
    # Success
    # --------------------------------------------------------

    logs += (
        "\nBUILD RESULT: SUCCESS"
    )

    if apk_path:

        logs += (
            f"\nAPK: {apk_path}"
        )

    return (
        True,
        apk_path,
        logs
    )
