import threading
import traceback

from modules.agent import BugFixAgent
from modules.models import Incident


class VAMPIntegration:
    """
    Connects the generic Android BugMonitor to the
    VAMP BugFixAgent.

    Flow:

        BugMonitor
             |
             v
          Incident
             |
             v
       VAMPIntegration
             |
             v
        BugFixAgent
             |
             v
      Analyze -> Patch -> Build -> Deploy -> Verify
    """

    def __init__(self, source_roots=None):
        """
        Initialize the VAMP integration layer.

        Args:
            source_roots:
                Optional list of source/project roots that can be
                used by BugFixAgent for source discovery.
        """

        self.source_roots = source_roots

        # Indicates whether a repair pipeline is currently running.
        self.active = False

        # Background worker running the VAMP repair pipeline.
        self.worker = None

        # Protects active/worker/result state from concurrent
        # BugMonitor callbacks.
        self._lock = threading.Lock()

        # Last completed result from BugFixAgent.
        self.last_result = None

        # Last error generated by the VAMP pipeline.
        self.last_error = None

    def handle_incident(self, incident: Incident):
        """
        Entry point called by BugMonitor when a failure is detected.

        The repair pipeline runs in a background thread so the
        monitoring layer remains responsive.

        Duplicate incidents are ignored while a repair is active.
        """

        if incident is None:
            print()
            print("⚠ VAMP received an empty incident.")
            return

        with self._lock:

            if self.active:
                print()
                print(
                    "⚠ VAMP repair pipeline is already running."
                )

                print(
                    "Ignoring duplicate incident."
                )

                return

            self.active = True
            self.last_result = None
            self.last_error = None

            self.worker = threading.Thread(
                target=self._run_agent,
                args=(incident,),
                daemon=True,
                name="VAMP-Repair-Agent"
            )

            self.worker.start()

    def _run_agent(self, incident: Incident):
        """
        Execute the VAMP repair pipeline.

        BugFixAgent owns the actual repair workflow.
        VAMPIntegration is only responsible for connecting
        Incident -> BugFixAgent and managing the background worker.
        """

        self._print_incident(incident)

        try:

            print()
            print("→ Starting VAMP repair...")

            agent = BugFixAgent(
                incident=incident,
                source_roots=self.source_roots
            )

            result = agent.run()

            self.last_result = result

            print()
            print("✓ VAMP pipeline finished")
            print("Result:", "SUCCESS" if result else "FAILED")

        except Exception as e:

            self.last_error = e

            print()
            print("=" * 70)
            print("             VAMP PIPELINE ERROR")
            print("=" * 70)

            print(
                "Error:",
                e
            )

            print()
            print("Traceback:")

            traceback.print_exc()

            print("=" * 70)

        finally:

            with self._lock:
                self.active = False

    def _print_incident(self, incident: Incident):
        """
        Print a concise incident status.

        Incident data itself is preserved and passed unchanged
        to BugFixAgent. Only terminal output is simplified.
        """

        bug_type = getattr(
            incident,
            "bug_type",
            None
        )

        package = getattr(
            incident,
            "package",
            None
        )

        print()
        print("✓ Incident detected")

        if bug_type:
            print(
                "  Type:",
                bug_type
            )

        if package:
            print(
                "  Package:",
                package
            )

    def _print_incident_field(name, value):
        """
        Print an incident field while safely handling missing
        information.

        Missing information is expected in a generic Android
        failure pipeline, so it should not cause the pipeline
        to fail.
        """

        if value is None:
            value = "Unknown"

        print(
            f"{name:<15}: {value}"
        )

    def is_active(self):
        """
        Return True when a VAMP repair is currently running.
        """

        with self._lock:
            return self.active

    def wait(self, timeout=None):
        """
        Wait for the current VAMP repair thread to finish.

        Args:
            timeout:
                Maximum time to wait in seconds.
                None waits indefinitely.

        Returns:
            True if the worker finished or no worker exists.
            False if the timeout expired.
        """

        worker = self.worker

        if worker is None:
            return True

        worker.join(timeout)

        return not worker.is_alive()

    def get_last_result(self):
        """
        Return the last BugFixAgent result.
        """

        return self.last_result

    def get_last_error(self):
        """
        Return the last VAMP pipeline error.
        """

        return self.last_error
